<a href="https://colab.research.google.com/github/PRAN20/All-Classification/blob/main/All_Classification_Model-.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calculating Accuracy by Using Different Classification**

# **Importing Header Files**

In [82]:
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt
import os

# **Importing DataSet**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
os.makedirs('dataset')

In [5]:
!unzip "/content/drive/MyDrive/dataset.zip" -d "dataset"

Archive:  /content/drive/MyDrive/dataset.zip
  inflating: dataset/dataset/test_features.csv  
  inflating: dataset/dataset/train_gender (2).csv  
  inflating: dataset/dataset/train_gender_labels (2).csv  
  inflating: dataset/dataset/true_values.csv  


In [6]:
x_train = ps.read_csv("/content/dataset/dataset/train_gender (2).csv")

In [7]:
y_train = ps.read_csv("/content/dataset/dataset/train_gender_labels (2).csv")

In [8]:
x_test = ps.read_csv("/content/dataset/dataset/test_features.csv")

In [9]:
y_test = ps.read_csv("/content/dataset/dataset/true_values.csv")

**Determing The Shape of all The Data**

In [10]:
x_train.shape

(47008, 512)

In [97]:
y_train.shape

(47008, 1)

In [12]:
x_test.shape

(2001, 512)

In [13]:
y_test.shape

(2001, 1)

# **Training The MLP Model**

In [98]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(max_iter = 500, activation = 'relu')
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPClassifier(max_iter=500)

**Testing the Model**

In [99]:
y_pred = classifier.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [100]:
print(y_pred)
y_pred.shape

[1. 1. 1. ... 0. 0. 0.]


(2001,)

**Confusion Matrix**

In [101]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[754, 247],
       [ 19, 981]])

**Calculating the Accuracy of the Model**

In [102]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.98      0.75      0.85      1001
         1.0       0.80      0.98      0.88      1000

    accuracy                           0.87      2001
   macro avg       0.89      0.87      0.87      2001
weighted avg       0.89      0.87      0.87      2001



In [104]:
from sklearn.metrics import accuracy_score
mlp = accuracy_score(y_test, y_pred)
mlp

0.8670664667666167

# **Naive-Bays Model**

In [105]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [106]:
y_pred = clf.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [108]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
naive = accuracy_score(y_test, y_pred)
naive

[[714 287]
 [ 18 982]]


0.847576211894053

In [109]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.98      0.71      0.82      1001
         1.0       0.77      0.98      0.87      1000

    accuracy                           0.85      2001
   macro avg       0.87      0.85      0.84      2001
weighted avg       0.87      0.85      0.84      2001



# **Random Forest Classification**

In [156]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 70, oob_score = True, n_jobs = -1,max_features = None, min_samples_leaf = 30)
clf1.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(max_features=None, min_samples_leaf=30, n_estimators=70,
                       n_jobs=-1, oob_score=True)

In [157]:
y_pred = clf1.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [159]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
rand = accuracy_score(y_test, y_pred)
rand

[[748 253]
 [ 22 978]]


0.862568715642179

In [29]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.75      0.85      1001
         1.0       0.80      0.98      0.88      1000

    accuracy                           0.87      2001
   macro avg       0.88      0.87      0.86      2001
weighted avg       0.88      0.87      0.86      2001



# **K-NN**

In [119]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
kn.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=15)

In [120]:
y_pred = kn.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [122]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
knn = accuracy_score(y_test, y_pred)
knn

[[767 234]
 [ 26 974]]


0.8700649675162418

In [123]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.77      0.86      1001
         1.0       0.81      0.97      0.88      1000

    accuracy                           0.87      2001
   macro avg       0.89      0.87      0.87      2001
weighted avg       0.89      0.87      0.87      2001



# **Decision Tree**

In [130]:
from sklearn.tree import DecisionTreeClassifier
clf2 = DecisionTreeClassifier(max_depth = 10, random_state = 101, max_features = None, min_samples_leaf = 15)
clf2.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=15, random_state=101)

In [131]:
y_pred = clf2.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [133]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
desc = accuracy_score(y_test, y_pred)
desc

[[755 246]
 [ 37 963]]


0.8585707146426786

In [134]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.75      0.84      1001
         1.0       0.80      0.96      0.87      1000

    accuracy                           0.86      2001
   macro avg       0.87      0.86      0.86      2001
weighted avg       0.87      0.86      0.86      2001



# **Kernel SVM**

In [164]:
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'linear', C =  1,  random_state = 101)
classifier1.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1, kernel='linear', random_state=101)

In [165]:
y_pred = classifier1.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [166]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svm = accuracy_score(y_test, y_pred)
svm

[[782 219]
 [ 22 978]]


0.879560219890055

In [167]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.78      0.87      1001
         1.0       0.82      0.98      0.89      1000

    accuracy                           0.88      2001
   macro avg       0.89      0.88      0.88      2001
weighted avg       0.89      0.88      0.88      2001



# **Linear SVC**

In [140]:
from sklearn.svm import LinearSVC
class3 = LinearSVC(random_state=0, tol=1e-5)
class3.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC(random_state=0, tol=1e-05)

In [141]:
y_pred = class3.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [144]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
svc = accuracy_score(y_test, y_pred)
svc

[[782 219]
 [ 23 977]]


0.8790604697651174

In [145]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.78      0.87      1001
         1.0       0.82      0.98      0.89      1000

    accuracy                           0.88      2001
   macro avg       0.89      0.88      0.88      2001
weighted avg       0.89      0.88      0.88      2001



# **Logistic Regression**

In [146]:
from sklearn.linear_model import LogisticRegression
classifier4 = LogisticRegression(random_state = 0)
classifier4.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [147]:
y_pred = classifier4.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [149]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
logis = accuracy_score(y_test, y_pred)
logis

[[764 237]
 [ 21 979]]


0.8710644677661169

In [150]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.76      0.86      1001
         1.0       0.81      0.98      0.88      1000

    accuracy                           0.87      2001
   macro avg       0.89      0.87      0.87      2001
weighted avg       0.89      0.87      0.87      2001



# **Stochastic Gradient Descent**

In [151]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state = 101)
sgd.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier(loss='modified_huber', random_state=101)

In [152]:
y_pred = sgd.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- -1.025214493274688721e-01
- -1.033663004636764526e-02
- -1.036800295114517212e-01
- -1.066513806581497192e-01
- -1.070177853107452393e-01
- ...
Feature names seen at fit time, yet now missing:
- -1.000557318329811096e-01
- -1.001642495393753052e-01
- -1.001687198877334595e-01
- -1.003685966134071350e-01
- -1.003979146480560303e-01
- ...

  warnings.warn(message, FutureWarning)


In [154]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
stoc = accuracy_score(y_test, y_pred)
stoc

[[812 189]
 [ 28 972]]


0.8915542228885557

In [155]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.97      0.81      0.88      1001
         1.0       0.84      0.97      0.90      1000

    accuracy                           0.89      2001
   macro avg       0.90      0.89      0.89      2001
weighted avg       0.90      0.89      0.89      2001



# **Final Results**

In [168]:
print('Accuracy of MLP Model is {}'.format(mlp))
print('Accuracy of Naive-Bays Model is {}'.format(naive))
print('Accuracy of Random Forest Model is {}'.format(rand))
print('Accuracy of K-NN Model is {}'.format(knn))
print('Accuracy of Decision Tree Model is {}'.format(desc))
print('Accuracy of Kernel Svm Model is {}'.format(svm))
print('Accuracy of Linear SVC Model is {}'.format(svc))
print('Accuracy of Logistic Regression Model is {}'.format(logis))
print('Accuracy of Stochastic Gradient Descent Model is {}'.format(stoc))

Accuracy of MLP Model is 0.8670664667666167
Accuracy of Naive-Bays Model is 0.847576211894053
Accuracy of Random Forest Model is 0.862568715642179
Accuracy of K-NN Model is 0.879560219890055
Accuracy of Decision Tree Model is 0.8585707146426786
Accuracy of Kernel Svm Model is 0.879560219890055
Accuracy of Linear SVC Model is 0.8790604697651174
Accuracy of Logistic Regression Model is 0.8710644677661169
Accuracy of Stochastic Gradient Descent Model is 0.8915542228885557
